### DISCUSSION TITLE
Resource not accessible by integration

### DISCUSSION THREAD

**Discussion by idanbuberman** [kishikawakatsumi/xcresulttool#630] [Q&A]
We have unit + UI tests running on wrapper using my SPM package.
Tests running solid and file is accessible when echo-ing it etc.
But for some reason when running this action on this specific repo - the results are inaccessible. (Both when tests passed or failed)

We are using this action on different repos, on some we are running on default directory and in some in sub-directories and everything works. I tried the same here - did not help.

```
      - name: Create Human-Readable Report
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: '/Users/runner/work/misnap-spm/misnap-spm/Developer/TestResults.xcresult'
          show-passed-tests: false
        if: success() || failure()
```

Action's log:
![Screen Shot 2022-06-26 at 12 34 59](https://user-images.githubusercontent.com/6490582/175808224-d6a8246e-ee46-41a2-bb3a-6dc695c1096c.png)

Printing the report through bash commands:
![Screen Shot 2022-06-26 at 12 36 03](https://user-images.githubusercontent.com/6490582/175808263-967f4ab0-a376-461b-9d1c-1bbd36451981.png)

**Comment by amitBlueVine** [comment]
Same here…

**Comment by apparition47** [comment]
What does the `on:` trigger look like in your Action? If you're running your Action from a fork and `pull_request` instead of `pull_request_target`, for example, you'll encounter this issue because the `checks:write` permission is required.

**Comment by mrackwitz** [comment]
I'm seeing this issue as well after we migrated to GitHub Enterprise. 🤔

**Comment by mrackwitz** [comment]
The problem were missing workflow permissions. (needs to be **read and write**, obviously) It needs to be enabled on the enterprise level and can then only be more restrictive on organization and repository level.

<img width="1266" alt="Screen Shot 2023-02-06 at 16 26 51" src="https://user-images.githubusercontent.com/1389011/217318650-8e23aab8-1679-4dfc-af53-a2efec07698a.png">

**Comment by kishikawakatsumi** [comment]
@mrackwitz Thank you for investigating this issue. Am I correct in assuming that this means there is nothing I can do on my end, and that changing the settings for each repository will solve the problem?

**Comment by mrackwitz** [comment]
>Am I correct in assuming that this means there is nothing I can do on my end

Indeed! I think the only thing you could possibly do is add further documentation, but I hope already by just sharing my solution in this issue, others who run into it, will find it. Thanks for this amazing little tool, Katsumi. 🙏

**Comment by mrackwitz** [comment]
One more, if you use reusable workflows (e.g. via `workflow_call`) and [set explicit permissions](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview), then you need to have write access to `checks`.

```yaml
permissions:
  # other permissions...

  # This workflow needs write access to the checks to publish
  # the results of the tests via xcresulttool.
  checks: write
```
