### ISSUE TITLE
Question: Is it possible to print only high level summaries and failures?

### ISSUE THREAD

**Issue by ryanbooker** [kishikawakatsumi/xcresulttool#145]
We have hundreds of tests and if I try the following settings I still end up with hundreds of lines. It doesn't even get through the test listing before running out of characters. It seems to post a summary for every individual test class.

I'd like to post only the overall Code Coverage summary, overall Test Results summary, and test failures.

Am I doing something wrong, is this possible?

```
      - uses: kishikawakatsumi/xcresulttool@v1.3.1
        if: success() || failure()
        with:
          path: path/to/foo.xcresult
          show-code-coverage: true
          show-passed-tests: false
```

Thanks for the action, and any advice you may have. :)
