### ISSUE TITLE
Don't fail on missing .xcresult files if multiple are passed

### ISSUE THREAD

**Issue by benkay** [kishikawakatsumi/xcresulttool#178]
We have multiple test steps, and as a result end up with multiple .xcresult files.
I tried passing all the result bundle paths to a single xcresulttool action, but if not all the .xcresult files have been generated for a run, then the action immediately fails with a `no such file or directory` error.

This is a problem since if some test steps are skipped due to an earlier failure, not all of the possible .xcresult files will be generated, making the ability to pass multiple result bundles to the same xcresulttool step useless to us

**Comment by baksha97** [comment]
Have you tried `continue-on-failure`?
```yml
    - name: Any fallible 
      run: curl --fail www.blah.com
      continue-on-error: true
```
