### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by idanbuberman** [kishikawakatsumi/xcresulttool#324]
We have unit + UI tests running on wrapper using my SPM package.
Tests running solid and file is accessible when echo-ing it etc.
But for some reason when running this action on this specific repo - the results are inaccessible. (Both when tests passed or failed)

We are using this action on different repos, on some we are running on default directory and in some in sub-directories and everything works. I tried the same here - did not help.

```
      - name: Create Human-Readable Report
        uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: '/Users/runner/work/misnap-spm/misnap-spm/Developer/TestResults.xcresult'
          show-passed-tests: false
        if: success() || failure()
```

Action's log:
![Screen Shot 2022-06-26 at 12 34 59](https://user-images.githubusercontent.com/6490582/175808224-d6a8246e-ee46-41a2-bb3a-6dc695c1096c.png)

Printing the report through bash commands:
![Screen Shot 2022-06-26 at 12 36 03](https://user-images.githubusercontent.com/6490582/175808263-967f4ab0-a376-461b-9d1c-1bbd36451981.png)
