### ISSUE TITLE
Node version (12) too old for M1 Macs

### ISSUE THREAD

**Issue by Bigpet** [kishikawakatsumi/xcresulttool#359]
Tried to use this on a M1 Mac self-hosted runner

It just resulted in this:
```
Run kishikawakatsumi/xcresulttool@v1.4.0
The node12 is not supported on macOS ARM64 platform. Use node16 instead.
```

I'm not really sure which part of this code runs where, but if this https://github.com/kishikawakatsumi/xcresulttool/blob/82261e5a2d4c744744b226cfc4d8cc8aad433f13/.github/workflows/check-dist.yml runs on the runner, could you update the node version to at least 16 to make it possible to run this on M1 macs?

I also tried to apply 
```
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.x
```
before the `- uses: kishikawakatsumi/xcresulttool@v1.4.0` step, but that has no effect, so it's somewhere internal to xcresulttool
      
 
 
 This is probably more related: https://github.com/kishikawakatsumi/xcresulttool/blob/82261e5a2d4c744744b226cfc4d8cc8aad433f13/action.yml#L24
