### ISSUE TITLE
Unsupported file type

### ISSUE THREAD

**Issue by maxkazakov** [kishikawakatsumi/xcresulttool#42]
I run tests on M1 with Xcode 12.5.1

Step for xcresulttool:
```
- name: Pretty report 
      uses: kishikawakatsumi/xcresulttool@v1.0.3
      with:
        path: AllTests.xcresult
      if: success() || failure()
```

Result of the step gives me unspecified error:

![image](https://user-images.githubusercontent.com/17107905/140057277-1558e478-423c-4722-bd3a-f0da9a4a442d.png)
