### ISSUE TITLE
Error: The process '/usr/bin/xcrun' failed with exit code 1

### ISSUE THREAD

**Issue by paulz** [kishikawakatsumi/xcresulttool#438]
Thank you for the awesome action!

when using `show-passed-tests: false`

we are getting the error:

`Error: The process '/usr/bin/xcrun' failed with exit code 1`

in step:
```
      - name: xcresulttool
        uses: kishikawakatsumi/xcresulttool@v1.5.0
        if: always()
        with:
          show-passed-tests: false
          show-code-coverage: true
          upload-bundles: false
          path: |
            test-results/consumer-all-tests.xcresult
            test-results/trainer-all-tests.xcresult
```

when using `show-passed-tests: true` it works but output is truncated
