### ISSUE TITLE
path: attribute is not relative to working-directory: 

### ISSUE THREAD

**Issue by dominickendrick** [kishikawakatsumi/xcresulttool#602]
Hi,

Thanks for making this GitHub Action, it's very useful!

One thing I can across was that if you use the `working-directory` attribute in your action, the `path` attribute needs to also include the full path.

```
ios-reference-app-bundled-tests:
    name: Run Cover Drop reference bundled tests
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: UI Tests
        working-directory: ios/reference/  <<< When this is set ...
        run: >
          xcodebuild clean test
          -project reference.xcodeproj
          -scheme reference
          -resultBundlePath TestResults
          -destination 'platform=iOS Simulator,name=iPhone 14'
      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: ios/reference/TestResults.xcresult          <<< Path needed to be updated
          show-passed-tests: false
        if: success() || failure()
```
It would be good if the `path` attribute looked for files relative to the `working-directory`.
